### ISSUE TITLE
Disable schema generation

### ISSUE THREAD

**Issue by julienBaleizao** [streamthoughts/kafka-connect-file-pulse#128]
Hello,

I have created my own AVRO schema to ingest my CSV data.
I have registered my schema in the schema registry.

When I launch the connector I get the following error:
`Caused by: org.apache.kafka.common.errors.SerializationException: Error registering Avro schema: ["null",{"type":"record","name":"ConnectDefault","namespace":"io.confluent.connect.avro","fields":[{"name":"message","type":["null","string"],"default":null},{"name":"headers","type":["null",{"type":"array","items":["null","string"]}],"default":null}]}]
connect               | Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema being registered is incompatible with an earlier schema for subject "connect-file-pulse-data-csv-00-value"; error code: 409
`
I know that I have to set the property auto.register.schemas to false but I don't know how to do it with docker.

I am using the docker version (streamthoughts/kafka-connect-file-pulse) 1.6.3.

I have tried the following:
```
CONNECT_PRODUCER_AUTO_REGISTER_SCHEMAS: 'false'
CONNECT_PRODUCER_USE_LATEST_VERSION: 'true'
```
or 
```
CONNECT_AUTO_REGISTER_SCHEMAS: 'false'
CONNECT_USE_LATEST_VERSION: 'true'
```
Nothing is working.

How can I disable the schema generation ?

Thanks in advance.

**Comment by fhussonnois** [comment]
Hi @julienBaleizao, 

The properties `auto.register.schemas` and `use.latest.version` should be passed as follows : 

```
CONNECT_VALUE_CONVERTER_AUTO_REGISTER_SCHEMA=false
CONNECT_VALUE_CONVERTER_USE_LATEST_VERSION=true
```

Note that these properties are part of the Confluent Avro Converter not Kafka Connect FilePulse: https://docs.confluent.io/platform/current/schema-registry/connect.html#configuration-options

**Comment by julienBaleizao** [comment]
Hi,

I have set the properties but the Avro converter is still trying to register the schema.

See my docker configuration:
  ```
connect-file-pulse:
    image: streamthoughts/kafka-connect-file-pulse:1.6.3
    container_name: connect
    depends_on:
      - cp-broker
      - cp-schema-registry
    ports:
      - "8083:8083"
      - "8000:8000"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_AUTO_REGISTER_SCHEMA: "false"
      CONNECT_VALUE_CONVERTER_USE_LATEST_VERSION: "true"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # kafka-connect-file-pulse is installed as a confluent-hub component
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components/,/etc/kafka-connect"
```

Do you see something wrong in my configuration ?

Thanks.
