### ISSUE TITLE
Set column headers from second row in csv file

### ISSUE THREAD

**Issue by markns** [streamthoughts/kafka-connect-file-pulse#227]
Hi,
For some input files, I would like to set the column headers from the 2nd or 3rd row in the file. Is this possible?

I've been playing around with configuration such as the following, but haven't cracked it yet.

```
filters.SetHeader.type=io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter
filters.SetHeader.if={{ starts_with($value.message, '!headerRow) }}
filters.SetHeader.value=$.message
filters.SetHeader.field=$.headers

filters.Drop.type=io.streamthoughts.kafka.connect.filepulse.filter.DropFilter
filters.Drop.if={{ starts_with($value.message, '!') }}

filters.ParseDelimitedRow.extractColumnName=headers
filters.ParseDelimitedRow.trimColumn=true
filters.ParseDelimitedRow.separator=\\|
filters.ParseDelimitedRow.type=io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter
```

In this case, I guess the AppendFilter is only adding headers to the "!headerRow" record, which is then dropped. Subsequent records never see the header at all.

I was also thinking about adding the header to a `variable` with the AppendFilter, and then using another append filter to add the header back to the record.

Any thoughts, much appreciated!

ps. if there is a better forum for such questions please let me know. Gitter is always nice :)

**Comment by markns** [comment]
Also, would you perhaps be able to tell me if it's possible to create a filter pipeline that would achieve the following transformation?

source CSV

```
ModelVer:100
!ReleaseDate:20220217
!Id|Dimension|Value|DataDate
DA000050|GM_1|0.025010|20220216
DA000050|GM_2|-0.122080|20220216
```

desired record output

```
Record:
   Id: DA000050
   Dimension: GM_1
   Value: 0.025010
   DataDate: 20220216
   ModelVer: 100
   ReleaseDate: 20220217
Record:
   Id: DA000050
   Dimension: GM_2
   Value: -0.122080
   DataDate: 20220216
   ModelVer: 100
   ReleaseDate: 20220217
```

I definitely don't mind experimenting, but I'm starting to wonder if it's possible to achieve this currently.  I notice in particular the `Note: variables are not cached between records`
