### ISSUE TITLE
unable to use value.connect.schema in avro representation schema format

### ISSUE THREAD

**Issue by tuxfight3r** [streamthoughts/kafka-connect-file-pulse#592]
**Describe the bug**
Unable to use value.connect.schema setting with valid avro schema as jsonstring. getting the following Config Exception error

version used: kafka-connect-file-pulse:2.13.0

```
 org.apache.kafka.common.config.ConfigException: Invalid value com.jsoniter.spi.JsonException: ReflectionEnumDecoder: record is not valid enum for class org.apache.kafka.connect.data.Schema$Type,
```
### Full logs
```
connect            | 2024-01-29 15:57:45,194 INFO [DistributedHerder-connect-1-1] [Worker clientId=connect-1, groupId=compose-connect-group] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
connect            | 2024-01-29 15:57:45,195 INFO [task-thread-connect-file-pulse-quickstart-s3-v2-0] EnrichedConnectorConfig values: 
connect            | 	connect.schema.keep.leading.underscores.on.record.name = false
connect            | 	file.uris.provider = class io.streamthoughts.kafka.connect.filepulse.fs.DefaultTaskFileURIProvider
connect            | 	filters = [ParseCSVLine]
connect            | 	filters.ParseCSVLine.auto.generate.column.names = false
connect            | 	filters.ParseCSVLine.autoGenerateColumnNames = null
connect            | 	filters.ParseCSVLine.columns = eventid:STRING;iyear:STRING;iMonth:STRING;iday:STRING;approxdate:STRING;extended:STRING;resolution:STRING;country:STRING
connect            | 	filters.ParseCSVLine.duplicate.columns.as.array = false
connect            | 	filters.ParseCSVLine.duplicateColumnsAsArray = null
connect            | 	filters.ParseCSVLine.escape.char = \
connect            | 	filters.ParseCSVLine.extract.column.name = null
connect            | 	filters.ParseCSVLine.extractColumnName = null
connect            | 	filters.ParseCSVLine.if = null
connect            | 	filters.ParseCSVLine.ignore.leading.whitespace = true
connect            | 	filters.ParseCSVLine.ignore.quotations = false
connect            | 	filters.ParseCSVLine.ignoreFailure = false
connect            | 	filters.ParseCSVLine.invert = false
connect            | 	filters.ParseCSVLine.quote.char = "
connect            | 	filters.ParseCSVLine.separator = ,
connect            | 	filters.ParseCSVLine.strict.quotes = false
connect            | 	filters.ParseCSVLine.trim.column = true
connect            | 	filters.ParseCSVLine.trimColumn = null
connect            | 	filters.ParseCSVLine.type = class io.streamthoughts.kafka.connect.filepulse.filter.CSVFilter
connect            | 	filters.ParseCSVLine.withOnFailure = null
connect            | 	fs.listing.class = class io.streamthoughts.kafka.connect.filepulse.fs.AmazonS3FileSystemListing
connect            | 	fs.listing.filters = [io.streamthoughts.kafka.connect.filepulse.fs.filter.RegexFileListFilter]
connect            | 	ignore.committed.offsets = false
connect            | 	merge.value.connect.schemas = false
connect            | 	offset.policy.class = class io.streamthoughts.kafka.connect.filepulse.offset.DefaultSourceOffsetPolicy
connect            | 	task.generation.id = 0
connect            | 	task.partitioner.class = class io.streamthoughts.kafka.connect.filepulse.source.DefaultTaskPartitioner
connect            | 	tasks.empty.poll.wait.ms = 500
connect            | 	tasks.file.processing.order.by = LAST_MODIFIED
connect            | 	tasks.file.status.storage.class = class io.streamthoughts.kafka.connect.filepulse.state.KafkaFileObjectStateBackingStore
connect            | 	tasks.halt.on.error = false
connect            | 	tasks.reader.class = class io.streamthoughts.kafka.connect.filepulse.fs.reader.AmazonS3RowFileInputReader
connect            | 	topic = connect-file-pulse-quickstart-csv2
connect            | 	value.connect.schema = {"type":"record","name":"GlobalEvent","namespace":"io.test.dsp.event","fields":[{"name":"eventId","type":["null","string"],"default":null},{"name":"iyear","type":["null","string"],"default":null},{"name":"imonth","type":["null","string"],"default":null},{"name":"iday","type":["null","string"],"default":null},{"name":"approximateDate","type":["null","string"],"default":null},{"name":"extended","type":["null","string"],"default":null},{"name":"resolution","type":["null","string"],"default":null},{"name":"country","type":["null","string"],"default":null}]}
connect            | 	value.connect.schema.condition.topic.pattern = null
connect            | 	value.connect.schema.type = CONNECT
connect            |  (io.streamthoughts.kafka.connect.filepulse.config.SourceTaskConfig$EnrichedConnectorConfig)
connect            | 2024-01-29 15:57:45,195 INFO [task-thread-connect-file-pulse-quickstart-s3-v2-0] DefaultSourceOffsetPolicyConfig values: 
connect            | 	offset.attributes.string = uri
connect            |  (io.streamthoughts.kafka.connect.filepulse.offset.DefaultSourceOffsetPolicyConfig)
connect            | 2024-01-29 15:57:45,195 INFO [task-thread-connect-file-pulse-quickstart-s3-v2-0] Closing resources FilePulse source task (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask)
connect            | 2024-01-29 15:57:45,195 INFO [task-thread-connect-file-pulse-quickstart-s3-v2-0] Closed resources FilePulse source task (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask)
connect            | 2024-01-29 15:57:45,195 ERROR [task-thread-connect-file-pulse-quickstart-s3-v2-0] WorkerSourceTask{id=connect-file-pulse-quickstart-s3-v2-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
connect            | org.apache.kafka.common.config.ConfigException: Invalid value com.jsoniter.spi.JsonException: ReflectionEnumDecoder: record is not valid enum for class org.apache.kafka.connect.data.Schema$Type, head: 16, peek: ":"record", buf: {"type":"record","name":"GlobalEvent","namespace":"io.test.dsp.event","fields":[{"name":"eventId","type":["null","string"],"default":null},{"name":"iyear","type":["null","string"],"default":null},{"name":"imonth","type":["null","string"],"default":null},{"name":"iday","type":["null","string"],"default":null},{"name":"approximateDate","type":["null","string"],"default":null},{"name":"extended","type":["null","string"],"default":null},{"name":"resolution","type":["null","string"],"default":null},{"name":"country","type":["null","string"],"default":null}]} for configuration Failed to read connect-schema for 'value.connect.schema'
connect            | 	at io.streamthoughts.kafka.connect.filepulse.config.CommonSourceConfig.readConfigSchema(CommonSourceConfig.java:360)
connect            | 	at io.streamthoughts.kafka.connect.filepulse.config.CommonSourceConfig.getValueConnectSchema(CommonSourceConfig.java:320)
connect            | 	at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.start(FilePulseSourceTask.java:127)
connect            | 	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.initializeAndStart(AbstractWorkerSourceTask.java:274)
connect            | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
connect            | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
connect            | 	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:75)
connect            | 	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
connect            | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
connect            | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
connect            | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
connect            | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect            | 	at java.base/java.lang.Thread.run(Thread.java:829)
connect            | 2024-01-29 15:57:45,195 INFO [task-thread-connect-file-pulse-quickstart-s3-v2-0] Stopping FilePulse source task (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask)
connect            | 2024-01-29 15:57:45,196 INFO [task-thread-connect-file-pulse-quickstart-s3-v2-0] [Producer clientId=connector-producer-connect-file-pulse-quickstart-s3-v2-0] Closing the Kafka producer with timeoutMillis = 30000 ms. (org.apache.kafka.clients.producer.KafkaProducer)
connect            | 2024-01-29 15:57:45,196 INFO [kafka-producer-network-thread | connector-producer-connect-file-pulse-quickstart-s3-v2-0] [Producer clientId=connector-producer-connect-file-pulse-quickstart-s3-v2-0] Cluster ID: hXVHbzmsQcycAn4yR6K_Bg (org.apache.kafka.clients.Metadata)

```

**To Reproduce**
### docker compose config
```
  connect:
    image: streamthoughts/kafka-connect-file-pulse:2.13.0
    # networks:
    #  - demo
    platform: linux/amd64
    container_name: connect
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_INTERNAL_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      # kafka-connect-file-pulse is installed as a confluent-hub component
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components/"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      # CONNECT_LOG4J_LOGGERS: io.streamthoughts=DEBUG,org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
      # Uncomment for debugging the connector during development cycle
      # KAFKA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n"
    volumes:
      - ./test_data/data:/tmp/test_data/data
    networks:
     - demo
```

### kafka connect configuration for parsing a csv from AWS to kafka using a given schema.
```
{
  "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
  "filters": "ParseCSVLine",
  "filters.ParseCSVLine.auto.generate.column.names": false,
  "filters.ParseCSVLine.trim.column": "true",
  "filters.ParseCSVLine.seperator": ",",
  "filters.ParseCSVLine.type": "io.streamthoughts.kafka.connect.filepulse.filter.CSVFilter",
  "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.AmazonS3MoveCleanupPolicy",
  "fs.cleanup.policy.move.success.aws.prefix.path": "processed",
  "fs.cleanup.policy.move.failure.aws.prefix.path": "failed",
  "fs.cleanup.policy.triggered.on":"COMMITTED",
  "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.AmazonS3FileSystemListing",
  "fs.listing.filters":"io.streamthoughts.kafka.connect.filepulse.fs.filter.RegexFileListFilter",
  "fs.listing.interval.ms": "10000",
  "file.filter.regex.pattern":".*\\.csv$",
  "offset.policy.class":"io.streamthoughts.kafka.connect.filepulse.offset.DefaultSourceOffsetPolicy",
  "offset.attributes.string": "uri",
  "skip.headers": "1",
  "topic": "connect-file-pulse-quickstart-csv2",
  "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.AmazonS3RowFileInputReader",
  "tasks.file.status.storage.class": "io.streamthoughts.kafka.connect.filepulse.state.KafkaFileObjectStateBackingStore",
  "tasks.file.status.storage.bootstrap.servers": "broker:29092",
  "tasks.file.status.storage.topic": "connect-file-pulse-status2",
  "tasks.file.status.storage.topic.partitions": 10,
  "tasks.file.status.storage.topic.replication.factor": 1,
  "tasks.max": 1,
  "aws.access.key.id": "aws_access_key",
  "aws.secret.access.key": "aws_secret_key",
  "aws.s3.bucket.name": "dev-test-data-bucket",
  "aws.s3.region": "us-east-1",
  "aws.s3.bucket.prefix": "csv2/",
  "value.connect.schema": "{\"type\":\"record\",\"name\":\"GlobalEvent\",\"namespace\":\"io.test.dsp.event\",\"fields\":[{\"name\":\"eventId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"iyear\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"imonth\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"iday\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"approximateDate\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"extended\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"resolution\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"country\",\"type\":[\"null\",\"string\"],\"default\":null}]}",
  "filters.ParseCSVLine.columns": "eventid:STRING;iyear:STRING;iMonth:STRING;iday:STRING;approxdate:STRING;extended:STRING;resolution:STRING;country:STRING"

}
```

**Expected behavior**
Config getting loaded without any issues when the connector is setup.

**Screenshots**

**Additional context**
We are trying to process a CSV file from AWS and load it using a strict column mapping, if i dont define the schema for small set of data it works fine with auto generated column name, when there is more rows sometimes the text with in quotes has the same delimeter and the application is reading them with more columns than its supposed to have. Is there a way to use the given schema and also to ignore the delimeter when within quotes.

Any help would be much appreciated.
