### ISSUE TITLE
[Question] Error after adding ksqldb-cli and ksqldb-server with Error/Warning:

### ISSUE THREAD

**Issue by scheung38** [streamthoughts/kafka-connect-file-pulse#77]
After adding ksqldb-server and ksql-cli

Getting:

![Screenshot 2020-09-19 at 01 21 45](https://user-images.githubusercontent.com/1273014/93654640-7ce79e00-fa16-11ea-9d4a-c42223929929.png)

Can this be ignored?

   
```
  ksqldb-server:
     image: confluentinc/ksqldb-server:0.11.0
     container_name: ksqldb-server
     depends_on:
       - cp-broker
       - cp-schema-registry
       - connect-file-pulse
     ports:
       - "8088:8088"
    
     volumes:
       - "./extensions/:/opt/ksqldb-udfs"

     environment:
       KSQL_LISTENERS: http://0.0.0.0:8088
       KSQL_BOOTSTRAP_SERVERS: broker:29092
       KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
       KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
       KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
       KSQL_KSQL_CONNECT_URL: http://connect:8083
       KSQL_KSQL_SERVICE_ID: confluent_rmoff_01
       KSQL_KSQL_HIDDEN_TOPICS: '^_.*'
       # Configuration for UDFs
       KSQL_KSQL_EXTENSION_DIR: "/opt/ksqldb-udfs"
       KSQL_KSQL_FUNCTIONS_FORMULA_BASE_VALUE: 5


   ksqldb-cli:
     image: confluentinc/ksqldb-cli:0.11.0
     container_name: ksqldb-cli
     depends_on:
       - cp-broker
       - ksqldb-server
     entrypoint: /bin/sh
     tty: true
```
